# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow_new.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(948, 658)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Layout_graphs = QtWidgets.QGridLayout()
        self.Layout_graphs.setObjectName("Layout_graphs")
        self.pltB = GraphicsLayoutWidget(self.centralwidget)
        self.pltB.setObjectName("pltB")
        self.Layout_graphs.addWidget(self.pltB, 0, 0, 1, 1)
        self.plt = GraphicsLayoutWidget(self.centralwidget)
        self.plt.setAutoFillBackground(False)
        self.plt.setStyleSheet("border: 0px;")
        self.plt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plt.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plt.setLineWidth(0)
        self.plt.setObjectName("plt")
        self.Layout_graphs.addWidget(self.plt, 2, 0, 1, 1)
        self.pltD = GraphicsLayoutWidget(self.centralwidget)
        self.pltD.setObjectName("pltD")
        self.Layout_graphs.addWidget(self.pltD, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.Layout_graphs, 2, 1, 1, 1)
        self.Layout_controls = QtWidgets.QGridLayout()
        self.Layout_controls.setObjectName("Layout_controls")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setObjectName("l1")
        self.Layout_controls.addWidget(self.l1, 1, 1, 1, 1)
        self.pButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pButton_Start.setMinimumSize(QtCore.QSize(0, 0))
        self.pButton_Start.setObjectName("pButton_Start")
        self.Layout_controls.addWidget(self.pButton_Start, 2, 4, 1, 1)
        self.pButton_Reference = QtWidgets.QPushButton(self.centralwidget)
        self.pButton_Reference.setObjectName("pButton_Reference")
        self.Layout_controls.addWidget(self.pButton_Reference, 4, 3, 1, 1)
        self.pButton_Stop = QtWidgets.QPushButton(self.centralwidget)
        self.pButton_Stop.setObjectName("pButton_Stop")
        self.Layout_controls.addWidget(self.pButton_Stop, 4, 4, 1, 1)
        self.l = QtWidgets.QLabel(self.centralwidget)
        self.l.setObjectName("l")
        self.Layout_controls.addWidget(self.l, 1, 3, 1, 2)
        self.pButton_Clear = QtWidgets.QPushButton(self.centralwidget)
        self.pButton_Clear.setObjectName("pButton_Clear")
        self.Layout_controls.addWidget(self.pButton_Clear, 2, 3, 1, 1)
        self.pButton_PID_Set = QtWidgets.QPushButton(self.centralwidget)
        self.pButton_PID_Set.setObjectName("pButton_PID_Set")
        self.Layout_controls.addWidget(self.pButton_PID_Set, 7, 0, 1, 1)
        self.cBox_Port = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_Port.setEditable(True)
        self.cBox_Port.setObjectName("cBox_Port")
        self.Layout_controls.addWidget(self.cBox_Port, 2, 1, 1, 1)
        self.pButton_Tswitch_ON = QtWidgets.QPushButton(self.centralwidget)
        self.pButton_Tswitch_ON.setObjectName("pButton_Tswitch_ON")
        self.Layout_controls.addWidget(self.pButton_Tswitch_ON, 4, 0, 1, 1)
        self.doubleSpinBox_Temperature = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Temperature.setMinimum(5000.0)
        self.doubleSpinBox_Temperature.setMaximum(45000.0)
        self.doubleSpinBox_Temperature.setProperty("value", 20000.0)
        self.doubleSpinBox_Temperature.setObjectName("doubleSpinBox_Temperature")
        self.Layout_controls.addWidget(self.doubleSpinBox_Temperature, 6, 0, 1, 1)
        self.label_I_Share = QtWidgets.QLabel(self.centralwidget)
        self.label_I_Share.setObjectName("label_I_Share")
        self.Layout_controls.addWidget(self.label_I_Share, 6, 3, 1, 1)
        self.label_D_Share = QtWidgets.QLabel(self.centralwidget)
        self.label_D_Share.setObjectName("label_D_Share")
        self.Layout_controls.addWidget(self.label_D_Share, 6, 4, 1, 1)
        self.label_P_Share = QtWidgets.QLabel(self.centralwidget)
        self.label_P_Share.setObjectName("label_P_Share")
        self.Layout_controls.addWidget(self.label_P_Share, 6, 2, 1, 1)
        self.label_Cycling_Time = QtWidgets.QLabel(self.centralwidget)
        self.label_Cycling_Time.setObjectName("label_Cycling_Time")
        self.Layout_controls.addWidget(self.label_Cycling_Time, 6, 1, 1, 1)
        self.spinBox_Cycling_Time = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_Cycling_Time.setMinimum(1)
        self.spinBox_Cycling_Time.setMaximum(1000)
        self.spinBox_Cycling_Time.setProperty("value", 50)
        self.spinBox_Cycling_Time.setObjectName("spinBox_Cycling_Time")
        self.Layout_controls.addWidget(self.spinBox_Cycling_Time, 7, 1, 1, 1)
        self.spinBox_I_Share = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_I_Share.setMaximum(100000)
        self.spinBox_I_Share.setSingleStep(0)
        self.spinBox_I_Share.setProperty("value", 200)
        self.spinBox_I_Share.setObjectName("spinBox_I_Share")
        self.Layout_controls.addWidget(self.spinBox_I_Share, 7, 3, 1, 1)
        self.spinBox_D_Share = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_D_Share.setMaximum(100000)
        self.spinBox_D_Share.setProperty("value", 100)
        self.spinBox_D_Share.setObjectName("spinBox_D_Share")
        self.Layout_controls.addWidget(self.spinBox_D_Share, 7, 4, 1, 1)
        self.spinBox_P_Share = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_P_Share.setMaximum(100000)
        self.spinBox_P_Share.setProperty("value", 1000)
        self.spinBox_P_Share.setObjectName("spinBox_P_Share")
        self.Layout_controls.addWidget(self.spinBox_P_Share, 7, 2, 1, 1)
        self.pButton_Temperature_Set = QtWidgets.QPushButton(self.centralwidget)
        self.pButton_Temperature_Set.setObjectName("pButton_Temperature_Set")
        self.Layout_controls.addWidget(self.pButton_Temperature_Set, 5, 0, 1, 1)
        self.infostatus = QtWidgets.QLabel(self.centralwidget)
        self.infostatus.setObjectName("infostatus")
        self.Layout_controls.addWidget(self.infostatus, 5, 3, 1, 2)
        self.pButton_Temperature_OFF = QtWidgets.QProgressBar(self.centralwidget)
        self.pButton_Temperature_OFF.setProperty("value", 0)
        self.pButton_Temperature_OFF.setObjectName("pButton_Temperature_OFF")
        self.Layout_controls.addWidget(self.pButton_Temperature_OFF, 0, 3, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.Layout_controls.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.info11 = QtWidgets.QLabel(self.centralwidget)
        self.info11.setObjectName("info11")
        self.Layout_controls.addWidget(self.info11, 4, 1, 1, 1)
        self.cBox_Source = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_Source.setObjectName("cBox_Source")
        self.Layout_controls.addWidget(self.cBox_Source, 5, 1, 1, 1)
        self.cBox_Speed = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_Speed.setEditable(True)
        self.cBox_Speed.setObjectName("cBox_Speed")
        self.Layout_controls.addWidget(self.cBox_Speed, 5, 2, 1, 1)
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        self.l2.setObjectName("l2")
        self.Layout_controls.addWidget(self.l2, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.Layout_controls.addWidget(self.label, 1, 0, 1, 1)
        self.infobar = QtWidgets.QLabel(self.centralwidget)
        self.infobar.setObjectName("infobar")
        self.Layout_controls.addWidget(self.infobar, 0, 0, 1, 3)
        self.gridLayout.addLayout(self.Layout_controls, 11, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "openQCM NEXT"))
        self.l1.setText(_translate("MainWindow", "Serial COM Port"))
        self.pButton_Start.setText(_translate("MainWindow", "Start"))
        self.pButton_Reference.setText(_translate("MainWindow", "Set/Reset Reference"))
        self.pButton_Stop.setText(_translate("MainWindow", "Stop"))
        self.l.setText(_translate("MainWindow", "Control Buttons"))
        self.pButton_Clear.setText(_translate("MainWindow", "Clear Plots"))
        self.pButton_PID_Set.setText(_translate("MainWindow", "PID Set"))
        self.pButton_Tswitch_ON.setText(_translate("MainWindow", "Temperature Crtl OFF"))
        self.label_I_Share.setText(_translate("MainWindow", "I Share [mA/(K+sec)]"))
        self.label_D_Share.setText(_translate("MainWindow", "D Share [(mA*s)/K]"))
        self.label_P_Share.setText(_translate("MainWindow", "P Share [mA/K]"))
        self.label_Cycling_Time.setText(_translate("MainWindow", "Cycling Time [msec]"))
        self.pButton_Temperature_Set.setText(_translate("MainWindow", "Temperature Set"))
        self.infostatus.setText(_translate("MainWindow", "Program status "))
        self.pushButton_2.setText(_translate("MainWindow", "Temperature Ctrl ON"))
        self.info11.setText(_translate("MainWindow", "Operation mode"))
        self.l2.setText(_translate("MainWindow", "Frequency - Quartz Sensors"))
        self.label.setText(_translate("MainWindow", "Temperature Control"))
        self.infobar.setText(_translate("MainWindow", "Infobar"))

from pyqtgraph import GraphicsLayoutWidget
